spring:
  application:
    name: workflow-messaging-engine

  datasource:
    url: jdbc:postgresql://localhost:5432/workflow_db
    username: sunho
    password: ""
    driver-class-name: org.postgresql.Driver